spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_api?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
spring-doc:
  pathsToMatch: /person/**,/book/**
  swagger-ui:
    use-root-path: true