cors:
  originPatterns: http://localhost:8080,http://pedro.com.br,http://localhost:3000
security:
    jwt:
      token:
        secret-key: 53cr37
        expire-lenght: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_api?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
spring-doc:
  pathsToMatch: /person/**,/book/**
  swagger-ui:
    use-root-path: true